#!/bin/bash

if [ $? -eq 0 ]; then
  for file in $WORKSPACE_DIR/*.bin; do cp $file $OUTPUT_DIR;done
  arm-none-eabi-size $WORKSPACE_DIR/core-firmware.elf > $OUTPUT_DIR/memory-use.log

  # Normalize firmware binary name
  mv $OUTPUT_DIR/core-firmware.bin $OUTPUT_DIR/firmware.bin
fi
